version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uwsgi --ini=uwsgi.ini
    volumes:
    - ./:/var/www/freemarketapi/
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
    - "1337:80"
    depends_on:
      - web

  db:
    image: postgres:13.6-alpine
    environment:
      - POSTGRES_DB=django_prod
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=prod_django_8734
    volumes:
    - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: